name: Windows via Serveo

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Protocol
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin MyP@ssw0rd123

      - name: Install OpenSSH
        shell: powershell
        run: |
          choco install -y openssh
          & "C:\Program Files\OpenSSH-Win64\install-sshd.ps1"
          Start-Service sshd

      - name: Start Tunnel
        shell: cmd
        run: |
          "C:\Program Files\OpenSSH-Win64\ssh.exe" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -R 0:localhost:3389 serveo.net
